sudo: required
language: java
jdk:
  - openjdk8
services:
  - docker

before_install:
  - docker pull openjdk:8-jdk-alpine

script:
  - mvn test
  - mvn clean package

after_success:
  - docker build -t anushaunni/springboot:v1 .
  #Login into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take the images and push to docker hub
  - docker push anushaunni/springboot:v1
